# Generated by Django 4.1.4 on 2022-12-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('product_slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('strap_color', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('images', models.ImageField(upload_to='photos/products')),
                ('images1', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('images2', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('images3', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('images4', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
